### ISSUE TITLE
Baking error

### ISSUE THREAD

**Issue by fire** [RavinMaddHatter/Madhatters-Table-Top-RPG-Mini-Maker#1]
The baking is occurring on line 439 of new_character_menu script.

The export is occurring on line 445.

Tracking here.

**Comment by fire** [comment]
Testing using the build from https://github.com/godotengine/godot/actions/runs/10996471374

**Comment by fire** [comment]
![369908779-57458a2d-52ce-442b-9625-0760d1782b6c](https://github.com/user-attachments/assets/f55d2dd9-57d1-41bf-8618-ebae4bf467ae)

Noticed that you did not assign a skeleton or a skin to the mesh instance, so it's a baked mesh -- which makes sense?

**Comment by fire** [comment]
Changes are on a branch https://github.com/RavinMaddHatter/Madhatters-Table-Top-RPG-Mini-Maker/tree/4.4Beta

**Comment by fire** [comment]
There seems to be a missing feature to bake both blend shapes and skeleton poses.

**Comment by fire** [comment]
Why are you using the obj exporter and not the gltf exporter?

https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/exporting_3d_scenes.html

**Comment by RavinMaddHatter** [comment]
I am using an obj export because I have tools I understand better that work with obj, and long term my goal is to use this to make 3d prints.

**Comment by RavinMaddHatter** [comment]
Skins and uvs are not important to me project, so I didn't set them. It sounds like the Godot export is missing blends, vs poses. If I can just do poses, I would like to see how that works.

**Comment by RavinMaddHatter** [comment]
> Changes are on a branch https://github.com/RavinMaddHatter/Madhatters-Table-Top-RPG-Mini-Maker/tree/4.4Beta

What do you mean by this. Are you just copying from the other thread?

**Comment by fire** [comment]
Well, it isn't a Godot Engine issue, so I put an issue tracking your problem here.

**Comment by RavinMaddHatter** [comment]
Can you explain how to bake then the bug is unclear.

**Comment by RavinMaddHatter** [comment]
If I call the function as documented in Godot. It doesn't yield the results
as documented in godot. I am happy to learn what I am doing wrong, but you
have said "it seems it doesn't work with both blend shapes and poses" that
seems to be a godot bug, at best in documentation as no such limits are
described

**Comment by RavinMaddHatter** [comment]
> There seems to be a missing feature to bake both blend shapes and skeleton poses.

"there" is unclear. where is there? godot or my code? because pronouns are clear to the write but unclear to the reader without context clues.

**Comment by RavinMaddHatter** [comment]
So even with a skin it doesnt bake. But you can clearly see in the screen shot you posted there is a skeleton attached. And that skeleton is posed in my testing. 

How does one add a feature to bake poses @fire 

![image](https://github.com/user-attachments/assets/6d3d5833-46b1-424f-949c-04d0a413f056)

**Comment by RavinMaddHatter** [comment]
Aah found it. I am dumb
